[project]
name = "product-classifier"
version = "0.1.0"
description = "Production ML system for product description classification"
readme = "README.md"
authors = [
    { name = "ChunHan519", email = "tiowtiow0519@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "mlflow>=3.15.1",
    "pandas>=2.3.3",
    "scikit-learn>=1.7.2",
    "xgboost>=3.2.0",
]

[dependency-groups]
dev = [
    "pytest>=8.0.0",
]

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
